apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubia-w-rb
  namespace: prod
subjects:
- kind: User
  name: kubia
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io