apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coddy-w-rb
  namespace: dev
subjects:
- kind: User
  name: coddy
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coddy-ro-rb
  namespace: prod
subjects:
- kind: User
  name: coddy
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io