apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
          limits:
            memory: "128Mi"
            cpu: "10m"